language: node_js
node_js:
- stable
branches:
  only:
  - travis2
env:
  global:
    - REMOTE_PATH=testDir/TravisCITest
    - REMOTE_USER=travisci
    - REMOTE_HOST=165.22.77.10
before_install:
  - bash scripts/install.sh
after_success:
  - bash scripts/deploy.sh