language: node_js
node_js:
  - 12.10.0
jobs:
  include:
    - stage: start
      script: npm run start
    - stage: test
      script: npm test

deploy:
  local_dir: build_gh
  provider: pages
  app: herokutravistest
  github_tokens: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: travis2