language: node_js
node_js:
  - 12.10.0
branches:
  only:
    -build_gh
after_success:
  -bash scripts/deploy.sh
deploy:
  provider: pages
  skip_cleanup: true
  github_tokens: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: travis2